apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    #name: my-app
     run: my-app
spec:
  ports:
    - port: 3000
      targetPort: 8080
  type: NodePort
  selector:
    run: my-app

----------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: praveenkittu/cs2
        ports:
        - containerPort: 8080